services:
  #Database section
  
  #orderdb: sql server
  orderdb:
    container_name: orderdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin3000
    restart: always
    volumes:
      - sqlserver_data:/var/opt/mssql/data
    ports:
      - "1435:1433"

  #productdb: mysql
  productdb:
    container_name: productdb
    environment:
      - MYSQL_ROOT_USER=thomas
      - MYSQL_ROOT_PASSWORD=Admin3000
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/bitnami/mysql/data
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6

  #customerdb: postgres
  customerdb:
    container_name: customerdb
    #    user: "1001:1001" # By default
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=Admin3000
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql

  #basketdb: redis
  basketdb:
    container_name: basketdb
#    environment:
#      - REDIS_PASSWORD=Admin3000
#      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/usr/local/etc/redis

  #inventorydb: mongo
  inventorydb:
    container_name: inventorydb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  hangfiredb:
    container_name: hangfiredb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - hangfire_mongo_data:/data/db

  #Infrastructure section

  rabbitmq:
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=thomas
      - RABBITMQ_DEFAULT_PASS=Admin3000
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/
  
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=0xthomasit@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Admin3000
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
  
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  elasticsearch:
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic #default username
      - ELASTIC_PASSWORD=Admin3000
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=Admin3000
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
  
  # microservices api section
  product.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "DatabaseSettings:ConnectionString=Server=productdb;Port=3306;Database=ProductDB;Uid=thomas;Pwd=Admin3000;"
    depends_on:
      - productdb
    ports:
      - "6002:80"
    restart: always
  
  customer.api:
    container_name: customer.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "DatabaseSettings:ConnectionString=Server=customerdb;Port=5432;Database=CustomerDB;User Id=postgres;Password=Admin3000"
      - "HangfireSettings:Storage:ConnectionString=Server=customerdb;Port=5432;Database=CustomerDB;User Id=postgres;Password=Admin3000"
    depends_on:
      - customerdb
    ports:
      - "6003:80"
    restart: always

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "EventBusSettings:HostAddress=amqp://thomas:Admin3000@rabbitmq:5672"
      - "GrpcSettings:StockUrl=http://inventory.grpc"
      - BackgroundJobSettings:HangfireUrl=http://hangfire.api
      - BackgroundJobSettings:CheckoutUrl=http://localhost:6001
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "6004:80"
    restart: always
  
  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "DatabaseSettings:ConnectionString=Server=orderdb;Database=OrderDB;User Id=sa;Password=Admin3000;Encrypt=false;MultipleActiveResultSets=true;"
      - "EventBusSettings:HostAddress=amqp://thomas:Admin3000@rabbitmq:5672"
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - "6005:80"
    restart: always
    
  inventory.product.api:
    container_name: inventory.product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "MongoDbSettings:ConnectionString=mongodb://admin:admin@inventorydb:27017"
      - "MongoDbSettings:DatabaseName=InventoryDb"
    depends_on:
      - inventorydb
    ports:
      - "6006:80"
    restart: always
    
  inventory.grpc:
    container_name: inventory.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "MongoDbSettings:ConnectionString=mongodb://admin:admin@inventorydb:27017"
      - "MongoDbSettings:DatabaseName=InventoryDb"
    depends_on:
      - inventorydb
    ports:
      - "6007:80"
    restart: always
  
  apigw.ocelot:
    container_name: apigw.ocelot
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://+:80
      - "GlobalConfiguration:BaseUrl=http://apigw.ocelot"
    depends_on:
      - customer.api
      - basket.api
      - product.api
      - ordering.api
      - inventory.product.api
    ports:
      - "6001:80"
    restart: always
    
  hangfire.api:
    container_name: hangfire.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - HangfireSettings:Storage:ConnectionString=mongodb://admin:admin@hangfiredb:27017/hangfire-webapi?authSource=admin
    depends_on:
      - hangfiredb
    ports:
      - "6008:80"
    restart: always

  webstatus:
    container_name: webstatus
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - HealthChecksUI__HealthChecks__0__Name=Product Health Check
      - HealthChecksUI__HealthChecks__0__Uri=http://product.api/hc
      - HealthChecksUI__HealthChecks__1__Name=Customer Health Check
      - HealthChecksUI__HealthChecks__1__Uri=http://customer.api/hc
      - HealthChecksUI__HealthChecks__2__Name=Basket Health Check 
      - HealthChecksUI__HealthChecks__2__Uri=http://basket.api/hc
      - HealthChecksUI__HealthChecks__3__Name=Ordering Health Check
      - HealthChecksUI__HealthChecks__3__Uri=http://ordering.api/hc
      - HealthChecksUI__HealthChecks__4__Name=Inventory Health Check
      - HealthChecksUI__HealthChecks__4__Uri=http://inventory.product.api/hc
      - HealthChecksUI__HealthChecks__5__Name=Scheduled Job Health Check
      - HealthChecksUI__HealthChecks__5__Uri=http://hangfire.api/hc
    ports:
      - "6010:80"